spring.profiles.active=dev
fix.enabled=false
fix.config-file=fixmessages/quickfix.cfg
fix.response-timeout-seconds=30
fix.poll-interval-millis=500
fix.sender-comp-id=CLIENT
fix.target-comp-id=SERVER
fix.host=localhost
fix.port=9878
fix.begin-string=FIX.4.4
