# WebSocket Configuration
websocket.url=ws://prod-host:8080/ws/orders

# RabbitMQ Management API
rabbitmq.management.host=http://prod-rabbitmq:15672
rabbitmq.management.username=prod_user
rabbitmq.management.password=prod_pass
rabbitmq.management.vhost=/prod
rabbitmq.request.queue=order-request-queue
rabbitmq.response.queue=order-response-queue

# Timeout / Retry Configuration
polling.timeout.seconds=90
polling.interval.millis=2000
websocket.ack.timeout.seconds=20
